In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4, 5])

In [5]:
type(ar)  

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a = [1,2,3,4]

In [9]:
np.asarray(a)

array([1, 2, 3, 4])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4, 5]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [13]:
c =a

In [14]:
c

[1, 2, 3, 4]

In [15]:
a

[1, 2, 3, 4]

In [16]:
c[0] = 100

In [17]:
a

[100, 2, 3, 4]

In [18]:
d = np.copy(a)

In [19]:
a

[100, 2, 3, 4]

In [20]:
a[1] = 100

In [21]:
a

[100, 100, 3, 4]

In [22]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j : i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [24]:
iterable = (i*i for i in range (5))

In [25]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [26]:
np.fromstring('23 356',sep =' ')

array([ 23., 356.])

In [27]:
l = [1,2,3,4,5,6,7,8,9,10]

In [28]:
ar = np.array(l)

In [29]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
ar.ndim

1

In [31]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
ar2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [33]:
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
ar2.ndim

2

In [35]:
ar2.size

10

In [36]:
ar2.shape

(2, 5)

In [37]:
ar2.dtype

dtype('int64')

In [38]:
ar22 = np.array([[1.6,2,3],[4,5,9.6],[7,8,9]])

In [39]:
ar22

array([[1.6, 2. , 3. ],
       [4. , 5. , 9.6],
       [7. , 8. , 9. ]])

In [40]:
ar22.dtype

dtype('float64')

In [41]:
x = np.arange(1.0,10.0,0.1)

In [42]:
x

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [43]:
list(x)

[np.float64(1.0),
 np.float64(1.1),
 np.float64(1.2000000000000002),
 np.float64(1.3000000000000003),
 np.float64(1.4000000000000004),
 np.float64(1.5000000000000004),
 np.float64(1.6000000000000005),
 np.float64(1.7000000000000006),
 np.float64(1.8000000000000007),
 np.float64(1.9000000000000008),
 np.float64(2.000000000000001),
 np.float64(2.100000000000001),
 np.float64(2.200000000000001),
 np.float64(2.300000000000001),
 np.float64(2.4000000000000012),
 np.float64(2.5000000000000013),
 np.float64(2.6000000000000014),
 np.float64(2.7000000000000015),
 np.float64(2.8000000000000016),
 np.float64(2.9000000000000017),
 np.float64(3.0000000000000018),
 np.float64(3.100000000000002),
 np.float64(3.200000000000002),
 np.float64(3.300000000000002),
 np.float64(3.400000000000002),
 np.float64(3.500000000000002),
 np.float64(3.6000000000000023),
 np.float64(3.7000000000000024),
 np.float64(3.8000000000000025),
 np.float64(3.9000000000000026),
 np.float64(4.000000000000003),
 np.float64(4.100

In [44]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [45]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
on = np.ones((3,5,7))

In [49]:
on

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [50]:
on + 5

array([[[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6.]]])

In [51]:
on*4

array([[[4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4.]]])

In [52]:
np.empty((3,4))

array([[8.01125390e-312, 1.40229737e-314, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.60952352e-072, 6.25648646e-091,
        7.24744751e+169],
       [4.29181037e-038, 1.42245875e+160, 3.99910963e+252,
        8.34402697e-309]])

In [53]:
# Create an identity matrix of size 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
linespace = np.linspace(0, 10, 5)

In [55]:
linespace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
np.logspace(1, 100, 10,base =2)

array([2.00000000e+00, 4.09600000e+03, 8.38860800e+06, 1.71798692e+10,
       3.51843721e+13, 7.20575940e+16, 1.47573953e+20, 3.02231455e+23,
       6.18970020e+26, 1.26765060e+30])

In [57]:
import numpy as np
import pandas as pd


In [58]:
arr1 = np.random.randn(3,4)
pd.DataFrame(arr1)

0         1         2         3
0  0.385747 -0.841848 -0.896024 -1.399151
1  1.110642  2.120650 -0.206828  1.587815
2 -0.008773  0.601902  0.617223  0.546224

In [59]:
pd.DataFrame(np.random.randint(1,100,(300,400))).to_csv('test.csv')

In [60]:
arr = np.random.rand(3,4)

In [61]:
arr

array([[0.31900576, 0.59718876, 0.07492891, 0.63265874],
       [0.54922671, 0.13739687, 0.37302   , 0.18947697],
       [0.78665535, 0.83409958, 0.24481643, 0.32693029]])

In [64]:
arr.reshape(12,1)

array([[0.31900576],
       [0.59718876],
       [0.07492891],
       [0.63265874],
       [0.54922671],
       [0.13739687],
       [0.37302   ],
       [0.18947697],
       [0.78665535],
       [0.83409958],
       [0.24481643],
       [0.32693029]])

In [65]:
arr[1][1]

np.float64(0.1373968745764278)

In [66]:
arr3 = np.random.randint(1,100,(3,4))

In [67]:
arr3

array([[37, 61, 78, 52],
       [ 2, 58, 62,  1],
       [36, 51, 49, 65]], dtype=int32)

In [69]:
arr3[arr3>20]

array([37, 61, 78, 52, 58, 62, 36, 51, 49, 65], dtype=int32)

In [70]:
arr3[2:3,[1,2]]

array([[51, 49]], dtype=int32)

In [ ]:
arr1 = np.random.randint(1,2,(3,4))
arr2 = np.random.randint(1,2,(3,4))

In [72]:
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [73]:
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [74]:
arr1+arr2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=int32)

In [75]:
arr1-arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [76]:
arr1*arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [77]:
arr1/arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
arr1%arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [81]:
arr1/0

C:\Users\sriva\AppData\Local\Temp\ipykernel_19436\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [85]:
arr2 = np.random.randint(1,3,(5,7))

In [86]:
arr2

array([[2, 2, 1, 1, 1, 2, 1],
       [2, 1, 1, 1, 1, 2, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 2, 1, 1],
       [2, 1, 1, 1, 2, 1, 2]], dtype=int32)

In [87]:
np.sqrt(arr2)

array([[1.41421356, 1.41421356, 1.        , 1.        , 1.        ,
        1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        , 1.        ,
        1.41421356, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.        , 1.41421356,
        1.        , 1.        ],
       [1.41421356, 1.        , 1.        , 1.        , 1.41421356,
        1.        , 1.41421356]])

In [88]:
np.exp(arr2)

array([[7.3890561 , 7.3890561 , 2.71828183, 2.71828183, 2.71828183,
        7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183, 2.71828183, 2.71828183,
        7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
        2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 , 2.71828183, 7.3890561 ,
        2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183, 2.71828183, 7.3890561 ,
        2.71828183, 7.3890561 ]])

In [89]:
np.log2(arr2)

array([[1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 1.]])