In [92]:
#Arrray manipulation in Numpy
import numpy as np

In [93]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) 

In [94]:
arr1.ndim

1

In [95]:
np.expand_dims(arr1,axis=1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [96]:
np.expand_dims(arr1,axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [97]:
np.squeeze(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [99]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
np.squeeze(data)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
np.repeat(arr1,3)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11, 12,
       12, 12])

In [103]:
np.roll(arr1,2)

array([11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
np.diag(arr1)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12]])

In [105]:
arr2 = np.random.randint(1,10,(3,3))
arr3 = np.random.randint(1,10,(3,3))

In [106]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
arr2

array([[6, 4, 9],
       [2, 9, 1],
       [1, 4, 2]], dtype=int32)

In [108]:
arr3+arr2

array([[ 9,  8, 15],
       [10, 12,  9],
       [ 8,  7, 11]], dtype=int32)

In [109]:
arr2-arr3

array([[ 3,  0,  3],
       [-6,  6, -7],
       [-6,  1, -7]], dtype=int32)

In [110]:
arr2**arr3

array([[   216,    256, 531441],
       [   256,    729,      1],
       [     1,     64,    512]], dtype=int32)

In [111]:
arr2&arr3

array([[2, 4, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int32)

In [112]:
-arr2

array([[-6, -4, -9],
       [-2, -9, -1],
       [-1, -4, -2]], dtype=int32)

In [113]:
-arr3

array([[-3, -4, -6],
       [-8, -3, -8],
       [-7, -3, -9]], dtype=int32)

In [114]:
arr2|arr3

array([[ 7,  4, 15],
       [10, 11,  9],
       [ 7,  7, 11]], dtype=int32)

In [115]:
arr2>arr3

array([[ True, False,  True],
       [False,  True, False],
       [False,  True, False]])

In [116]:
arr = np.array(['rishi','sachin','sanjay'])

In [117]:
np.char.upper(arr)

array(['RISHI', 'SACHIN', 'SANJAY'], dtype='<U6')

In [118]:
np.char.title(arr)

array(['Rishi', 'Sachin', 'Sanjay'], dtype='<U6')

In [119]:
np.char.capitalize(arr)

array(['Rishi', 'Sachin', 'Sanjay'], dtype='<U6')

In [120]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292])

In [121]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396])

In [122]:
np.tan(arr1)

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01])

In [123]:
np.tanh(arr1)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ,
       0.99998771, 0.99999834, 0.99999977, 0.99999997, 1.        ,
       1.        , 1.        ])

In [124]:
np.log10(arr1)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269, 1.07918125])

In [125]:
np.exp(arr1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05])

In [126]:
np.power(arr1,2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [127]:
np.mean(arr1)

np.float64(6.5)

In [128]:
np.median(arr1)

np.float64(6.5)

In [129]:
np.max(arr1)

np.int64(12)

In [130]:
np.min(arr1)

np.int64(1)

In [131]:
np.dot(arr2,arr3)

array([[113,  63, 149],
       [ 85,  38,  93],
       [ 49,  22,  56]], dtype=int32)

In [132]:
#Sorting,Searching and Counting functions in Numpy

In [133]:
arr4 = np.array([1,2,3,45,45,67,88,8,9,99,100,230,60])

In [134]:
arr4

array([  1,   2,   3,  45,  45,  67,  88,   8,   9,  99, 100, 230,  60])

In [135]:
np.sort(arr4)

array([  1,   2,   3,   8,   9,  45,  45,  60,  67,  88,  99, 100, 230])

In [136]:
np.searchsorted(arr4, 45)

np.int64(3)

In [137]:
arr5 = np.array([1,2,3,4,5,0,0,0,0,10,11,12])

In [138]:
np.count_nonzero(arr5)

np.int64(8)

In [139]:
np.where(arr5>9)

(array([ 9, 10, 11]),)

In [140]:
np.extract(arr5>5,arr5)

array([10, 11, 12])

In [141]:
arr5.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680,                  0,
                        0,                  0,                  0,
       720575940379279360, 792633534417207296, 864691128455135232])

In [142]:
#copies and views in Numpy

In [143]:
arr5

array([ 1,  2,  3,  4,  5,  0,  0,  0,  0, 10, 11, 12])

In [144]:
b = arr5.view()

In [145]:
b

array([ 1,  2,  3,  4,  5,  0,  0,  0,  0, 10, 11, 12])

In [146]:
b[0] = 67

In [147]:
b

array([67,  2,  3,  4,  5,  0,  0,  0,  0, 10, 11, 12])